disabled:
  # Base config files, only necessary to inform config finding script
  - x-pack/solutions/search/test/api_integration/config.ts

defaultQueue: 'n2-4-spot'
enabled:
  - x-pack/solutions/search/test/functional_search/config.ts
  - x-pack/solutions/search/test/functional_search/config/config.basic.ts
  - x-pack/solutions/search/test/functional_search/config/config.search_playground.ts
  - x-pack/solutions/search/test/functional_search/config/config.feature_flags.ts
  - x-pack/solutions/search/test/api_integration/apis/search_playground/config.ts
  - x-pack/solutions/search/test/functional_solution_sidenav/config.ts
  - x-pack/solutions/search/test/accessibility/config.ts
  - x-pack/platform/test/onechat_api_integration/configs/config.stateful.ts
