disabled:
  # Base config files, only necessary to inform config finding script
  - x-pack/platform/test/serverless/functional/config.search.base.ts

defaultQueue: 'n2-4-spot'
enabled:
  - x-pack/solutions/search/test/serverless/api_integration/configs/config.ts
  - x-pack/solutions/search/test/serverless/api_integration/configs/config.feature_flags.ts
  - x-pack/solutions/search/test/serverless/functional/configs/config.ts
  - x-pack/solutions/search/test/serverless/functional/configs/config.search_features.ts
  - x-pack/solutions/search/test/serverless/functional/configs/config.feature_flags.ts
  - x-pack/solutions/search/test/serverless/functional/configs/config.screenshots.ts
  - x-pack/solutions/search/test/serverless/functional/configs/config.nav_v2.ts
  - x-pack/platform/test/serverless/api_integration/configs/search/config.group1.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.examples.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.saved_objects_management.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.context_awareness.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.config_compat_mode.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group1.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group2.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group3.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group4.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group5.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group6.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group7.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group8.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group9.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group10.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group11.ts
  - x-pack/platform/test/serverless/functional/configs/search/config.group12.ts
  - x-pack/platform/test/onechat_api_integration/configs/config.serverless.ts
