disabled:
  # Base config files, only necessary to inform config finding script
  - x-pack/test_serverless/functional/test_suites/observability/cypress/oblt_config.base.ts

  # Cypress configs, for now these are still run manually
  - x-pack/test_serverless/functional/test_suites/observability/cypress/config_headless.ts
  - x-pack/test_serverless/functional/test_suites/observability/cypress/config_runner.ts

defaultQueue: 'n2-4-spot'
enabled:
  - x-pack/test_serverless/api_integration/test_suites/observability/config.ts
  - x-pack/test_serverless/api_integration/test_suites/observability/config.feature_flags.ts
  - x-pack/test_serverless/api_integration/test_suites/observability/common_configs/config.group1.ts
  - x-pack/test_serverless/api_integration/test_suites/observability/fleet/config.ts
  - x-pack/test_serverless/api_integration/test_suites/observability/ai_assistant/config.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.examples.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.feature_flags.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.saved_objects_management.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.context_awareness.ts
  - x-pack/test_serverless/functional/test_suites/observability/common_configs/config.group1.ts
  - x-pack/test_serverless/functional/test_suites/observability/common_configs/config.group2.ts
  - x-pack/test_serverless/functional/test_suites/observability/common_configs/config.group3.ts
  - x-pack/test_serverless/functional/test_suites/observability/common_configs/config.group4.ts
  - x-pack/test_serverless/functional/test_suites/observability/common_configs/config.group5.ts
  - x-pack/test_serverless/functional/test_suites/observability/common_configs/config.group6.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.screenshots.ts
  - x-pack/test_serverless/functional/test_suites/observability/config.telemetry.ts
  # serverless config files that run deployment-agnostic tests
  - x-pack/test/api_integration/deployment_agnostic/configs/serverless/oblt.serverless.config.ts
  - x-pack/test/api_integration/deployment_agnostic/configs/serverless/oblt.apm.serverless.config.ts
