disabled:
  # Base config files, only necessary to inform config finding script
  - x-pack/platform/test/serverless/functional/config.chat.base.ts

  # Serverless tests only run on main
  - x-pack/solutions/chat/test/serverless/api_integration/configs/config.ts
  - x-pack/solutions/chat/test/serverless/api_integration/configs/config.feature_flags.ts
  - x-pack/platform/test/serverless/api_integration/configs/chat/config.group1.ts
  - x-pack/solutions/chat/test/serverless/functional/configs/config.ts
  - x-pack/solutions/chat/test/serverless/functional/configs/config.feature_flags.ts
  - x-pack/platform/test/serverless/functional/configs/chat/config.config_compat_mode.ts
  - x-pack/platform/test/serverless/functional/configs/chat/config.group1.ts

defaultQueue: 'n2-4-spot'
enabled:
