disabled:
  # Base config files, only necessary to inform config finding script
  - x-pack/platform/test/serverless/functional/config.oblt.base.ts
  - x-pack/platform/test/serverless/functional/config.logs_essentials.base.ts

  # Observability AI Assistant local-only tests
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/configs/serverless/oblt.ai_assistant_local.serverless.config.ts

  # Empty configs
  - x-pack/solutions/observability/test/serverless/api_integration/configs/config.feature_flags.ts

defaultQueue: 'n2-4-spot'
enabled:
  - x-pack/solutions/observability/test/serverless/api_integration/configs/config.ts
  - x-pack/solutions/observability/test/serverless/api_integration/configs/config.logs_essentials.ts
  - x-pack/platform/test/serverless/api_integration/configs/observability/config.group1.ts
  - x-pack/platform/test/serverless/api_integration/configs/observability/config.logs_essentials.group1.ts
  - x-pack/solutions/observability/test/serverless/api_integration/test_suites/fleet/config.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.cases_and_rules.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.ml_and_discover.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.logs_essentials.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.examples.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.feature_flags.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.saved_objects_management.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.context_awareness.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.config_compat_mode.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group1.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group2.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group3.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group4.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group5.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group6.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group7.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group8.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group9.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group10.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group11.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.group12.ts
  - x-pack/platform/test/serverless/functional/configs/observability/config.logs_essentials.group1.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.screenshots.ts
  - x-pack/solutions/observability/test/serverless/functional/configs/config.telemetry.ts
  # serverless config files that run deployment-agnostic tests
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/configs/serverless/oblt.serverless.config.ts
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/feature_flag_configs/serverless/oblt.ai_assistant.serverless.config.ts
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/configs/serverless/oblt.apm.serverless.config.ts
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/configs/serverless/oblt.synthetics.serverless.config.ts
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/feature_flag_configs/serverless/oblt.serverless.config.ts
  - x-pack/solutions/observability/test/api_integration_deployment_agnostic/configs/serverless/oblt.ai_agent.serverless.config.ts
