disabled:
  # Base config files, only necessary to inform config finding script

  # Serverless deployment-agnostic default config for api-integration tests
  - x-pack/platform/test/api_integration_deployment_agnostic/default_configs/serverless.config.base.ts
  # Serverless base config files
  - x-pack/test_serverless/api_integration/config.base.ts
  - x-pack/test_serverless/functional/config.base.ts
  - x-pack/test_serverless/shared/config.base.ts

enabled:
  - x-pack/platform/test/api_integration_deployment_agnostic/configs/serverless/oblt.config.ts
  - x-pack/platform/test/api_integration_deployment_agnostic/configs/serverless/search.config.ts
  - x-pack/platform/test/api_integration_deployment_agnostic/configs/serverless/security.config.ts
