# Define which plugins should be run or skipped in Scout CI pipeline
ui_tests:
  enabled:
    - apm
    - discover_enhanced
    - maps
    - observability
    - observability_onboarding
    - painless_lab
    - security_solution
    - streams_app
    - slo_app
  disabled:
