# Define which plugins and packages should be run or skipped in Kibana CI pipeline
plugins:
  enabled:
    - apm
    - console
    - dashboard
    - cloud_security_posture
    - discover_enhanced
    - entity_store
    - fleet
    - index_management
    - infra
    - lens
    - maps
    - observability
    - observability_onboarding
    - painless_lab
    - profiling
    - search_getting_started
    - search_homepage
    - security
    - security_solution
    - slo
    - spaces
    - streams
    - streams_app
    - transform
    - dashboard
    - workflows_extensions
  disabled:

packages:
  enabled:
    - kbn-streamlang-tests
  disabled:
    - kbn-scout # Internal scout tests are run in advance to validate Scout integrity (see .buildkite/scripts/steps/test/scout_test_run_builder.sh)
    - kbn-scout-release-testing # Release tests will run separately as part of the release process

# Define test configs to be excluded from automatic discovery & execution in CI environment (process.env.CI=true)
excluded_configs:
  - x-pack/solutions/security/plugins/cloud_security_posture/test/scout_cspm_agentless/ui/parallel.playwright.config.ts
