# Define which plugins and packages should be run or skipped in Kibana CI pipeline
plugins:
  enabled:
    - apm
    - console
    - discover_enhanced
    - maps
    - observability
    - observability_onboarding
    - painless_lab
    - profiling
    - security_solution
    - streams_app
    - slo
  disabled:

packages:
  enabled:
    - kbn-streamlang-tests
    - kbn-scout-release-testing
  disabled:
    - kbn-scout # Internal scout tests are run in advance to validate Scout integrity (see .buildkite/scripts/steps/test/scout_test_run_builder.sh)
