# Define which plugins and packages should be run or skipped in Kibana CI pipeline
plugins:
  enabled:
    - apm
    - discover_enhanced
    - maps
    - observability
    - observability_onboarding
    - painless_lab
    - security_solution
    - streams_app
    - slo
  disabled:

packages:
  enabled:
    - kbn-streamlang-tests
  disabled:
