# Define which plugins and packages should be run or skipped in Kibana CI pipeline
plugins:
  enabled:
    - console
    - discover_enhanced
    - maps
    - observability_onboarding
    - painless_lab
    - security_solution
    - streams_app
  disabled:

packages:
  enabled:
  disabled:
    - kbn-scout # Internal scout tests are run in advance to validate Scout integrity (see .buildkite/scripts/steps/test/scout_test_run_builder.sh)
    - kbn-scout-release-testing
