# Define which plugins and packages should be run or skipped in Kibana CI pipeline
plugins:
  enabled:
    - apm
    - console
    - discover_enhanced
    - maps
    - observability_onboarding
    - painless_lab
    - security_solution
    - streams_app
  disabled:

packages:
  enabled:
    - kbn-scout-release-testing
  disabled:
