# Workplace AI Project Config

# Make sure the plugins belonging to this project type are loaded
plugins.allowlistPluginGroups: ['platform', 'workplaceai']

## Enable the Serverless Workplace AI plugin
xpack.serverless.workplaceAI.enabled: true

## Cloud settings
xpack.cloud.serverless.project_type: workplaceai

## Set the home route
uiSettings.overrides.defaultRoute: /app/workplace_ai

## Enable tech-preview pages
uiSettings.overrides:
  workflows:ui:enabled: true

## Enable workplace_ai plugins
xpack.workplaceAIApp.enabled: true

# Disable spaces
xpack.spaces.maxSpaces: 1

## Content Connectors in stack management
xpack.contentConnectors.enabled: false

## Disable Kibana Product Intercept
xpack.product_intercept.enabled: false

# Elastic Managed LLM
xpack.actions.preconfigured:
  Elastic-Managed-LLM:
    name: Elastic Managed LLM
    actionTypeId: .inference
    exposeConfig: true
    config:
      provider: "elastic"
      taskType: "chat_completion"
      inferenceId: ".rainbow-sprinkles-elastic"
      providerConfig:
        model_id: "rainbow-sprinkles"
