# Observability Project config

# Make sure the plugins belonging to this project type are loaded
plugins.allowlistPluginGroups: ['platform', 'observability']

## Enabled plugins
xpack.infra.enabled: true

# Disabled Observability plugins
xpack.ux.enabled: false
xpack.legacy_uptime.enabled: false

## Fine-tune the observability solution feature privileges. Also, refer to `serverless.yml` for the project-agnostic overrides.
xpack.features.overrides:
  ### By default, this feature named as `APM and User Experience`, but should be renamed to `Applications`.
  apm.name: 'Applications'
  ### Dashboards feature should be moved from Analytics category to the Observability one.
  dashboard_v2.category: 'observability'
  ### Discover feature should be moved from Analytics category to the Observability one and its privileges are
  ### fine-tuned to grant access to Observability app.
  discover_v2.category: 'observability'
  ### By default, this feature named as `Metrics`, but should be renamed to `Infrastructure`.
  infrastructure.name: 'Infrastructure'
  ### Machine Learning feature should be moved from Analytics category to the Observability one and renamed to `AI Ops`.
  ml:
    category: 'observability'
    order: 1200
  ### Stack alerts is hidden in Role management since it's not needed.
  stackAlerts.hidden: true
  ### By default, this feature named as `Synthetics and Uptime`, but should be renamed to `Synthetics` since `Uptime` is not available.
  uptime.name: 'Synthetics'

## Enable the slo plugin
xpack.slo.enabled: true

## Cloud settings
xpack.cloud.serverless.project_type: observability

## Enable the Serverless Observability plugin
xpack.serverless.observability.enabled: true

## Configure plugins

## Set the home route
uiSettings.overrides.defaultRoute: /app/observability/landing

# Customize empty page state for analytics apps
no_data_page.analyticsNoDataPageFlavor: 'serverless_observability'

## Disable adding the component template `.fleet_agent_id_verification-1` to every index template for each datastream for each integration
xpack.fleet.agentIdVerificationEnabled: false

## Enable event.ingested separately because agentIdVerification is disabled
xpack.fleet.eventIngestedEnabled: true

## APM Serverless Onboarding flow
xpack.apm.serverlessOnboarding: true

# Synthetics mTLS cert locations
xpack.uptime.service.tls.certificate: /mnt/elastic-internal/http-certs/tls.crt
xpack.uptime.service.tls.key: /mnt/elastic-internal/http-certs/tls.key

# Fleet specific configuration
xpack.fleet.internal.registry.capabilities: ['apm', 'observability', 'uptime']
xpack.fleet.internal.registry.spec.min: '3.0'
xpack.fleet.internal.registry.spec.max: '3.3'
xpack.fleet.internal.registry.kibanaVersionCheckEnabled: false
xpack.fleet.internal.registry.excludePackages: [
    # Security integrations
    'endpoint',
    'beaconing',
    'cloud_security_posture',
    'cloud_defend',
    'security_detection_engine',

    # Deprecated security integrations
    'bluecoat',
    'cisco',
    'cyberark',
    'cylance',
    'f5',
    'fortinet_forticlient',
    'juniper_junos',
    'juniper_netscreen',
    'microsoft',
    'netscout',
    'radware',
    'symantec',
    'tomcat',

    # ML integrations
    'dga',

    # Profiling integrations
    'profiler_agent',
  ]

## Required for force installation of integration packages
xpack.fleet.packages:
  # fleet_server package installed to publish agent metrics
  - name: fleet_server
    version: latest
## Disable APM UI components and API calls
xpack.apm.featureFlags.agentConfigurationAvailable: false
xpack.apm.featureFlags.configurableIndicesAvailable: false
xpack.apm.featureFlags.infrastructureTabAvailable: true
xpack.apm.featureFlags.infraUiAvailable: true
xpack.apm.featureFlags.migrationToFleetAvailable: false
xpack.apm.featureFlags.sourcemapApiAvailable: false
xpack.apm.featureFlags.storageExplorerAvailable: false

## Set the AI Assistant type
aiAssistantManagementSelection.preferredAIAssistantType: 'observability'
xpack.observabilityAIAssistant.scope: 'observability'

# Specify in telemetry the project type
telemetry.labels.serverless: observability

xpack.ml.ad.enabled: true
xpack.ml.dfa.enabled: true
xpack.ml.nlp:
  enabled: true
  modelDeployment:
    allowStaticAllocations: false
    vCPURange:
      low:
        min: 0
        max: 2
      medium:
        min: 1
        max: 32
      high:
        min: 1
        max: 128
xpack.ml.compatibleModuleType: 'observability'

# Disable the embedded Dev Console
console.ui.embeddedEnabled: false

# Disable role management (custom roles)
xpack.security.roleManagementEnabled: false
