# Security Project config

# Make sure the plugins belonging to this project type are loaded
plugins.allowlistPluginGroups: ['platform', 'security']

# Ess plugins
xpack.securitySolutionEss.enabled: false

## Disable plugins
xpack.observabilityAIAssistant.enabled: false

## Fine-tune the security solution feature privileges. These feature privilege overrides are set individually for each project type. Also, refer to `serverless.yml` for the project-agnostic overrides.
xpack.features.overrides:
  ### Machine Learning feature is moved from Analytics category to the Security one as the last item.
  ml:
    category: "security"
    order: 1101
## Cloud settings
xpack.cloud.serverless.project_type: security

## Enable the Security Solution Serverless plugin
xpack.securitySolutionServerless.enabled: true
xpack.securitySolutionServerless.productTypes:
  [
    { product_line: 'security', product_tier: 'complete' },
    { product_line: 'endpoint', product_tier: 'complete' },
    { product_line: 'cloud', product_tier: 'complete' },
  ]

xpack.securitySolution.offeringSettings: {
  ILMEnabled: false, # Index Lifecycle Management (ILM) functionalities disabled, not supported by serverless Elasticsearch
}

newsfeed.enabled: true

## Set the home route
uiSettings.overrides.defaultRoute: /app/security/get_started

# Specify in telemetry the project type
telemetry.labels.serverless: security

# Fleet specific configuration
xpack.fleet.internal.registry.capabilities: ['security']
xpack.fleet.internal.registry.spec.min: '3.0'
xpack.fleet.internal.registry.spec.max: '3.3'
xpack.fleet.internal.registry.kibanaVersionCheckEnabled: false
xpack.fleet.internal.registry.excludePackages: [
    # Oblt integrations
    'apm',
    'synthetics',
    'synthetics_dashboards',

    # Deprecated security integrations
    'bluecoat',
    'cisco',
    'cyberark',
    'cylance',
    'f5',
    'fortinet_forticlient',
    'juniper_junos',
    'juniper_netscreen',
    'microsoft',
    'netscout',
    'radware',
    'symantec',
    'tomcat',

    # ML integrations
    'dga',

    # Unsupported in serverless
    'cloud_defend',
  ]
# fleet_server package installed to publish agent metrics
xpack.fleet.packages:
  - name: fleet_server
    version: latest

xpack.ml.ad.enabled: true
xpack.ml.dfa.enabled: true
xpack.ml.nlp:
  enabled: true
  modelDeployment:
    allowStaticAllocations: false
    vCPURange:
      low:
        min: 0
        max: 2
      medium:
        min: 1
        max: 32
      high:
        min: 1
        max: 128
xpack.ml.compatibleModuleType: 'security'

# Disable the embedded Dev Console
console.ui.embeddedEnabled: false

# Enable project level rentention checks in DSL form from Index Management UI
xpack.index_management.enableProjectLevelRetentionChecks: true

# Increase task manager capacity because security projects have more resources (Memory and CPU)
xpack.task_manager.capacity: 20

## Enable uiSettings validations
xpack.securitySolution.enableUiSettingsValidations: true
