# Workplace AI Project Config

# Make sure the plugins belonging to this project type are loaded
plugins.allowlistPluginGroups: ['platform', 'workplaceai']

## Enable the Serverless Workplace AI plugin
xpack.serverless.workplaceAI.enabled: true

## Cloud settings
xpack.cloud.serverless.project_type: workplaceai

## Set the home route
uiSettings.overrides.defaultRoute: /app/workplace_ai

## Enable tech-preview pages
uiSettings.overrides:
  workflows:ui:enabled: true
  dataConnectors:enabled: true

## Enable workplace_ai plugins
xpack.workplaceAIApp.enabled: true

# Disable spaces
xpack.spaces.maxSpaces: 1

## Content Connectors in stack management
xpack.contentConnectors.enabled: false

## Disable Kibana Product Intercept
xpack.product_intercept.enabled: false

# Elastic Managed LLMs
xpack.actions.preconfigured:
  General-Purpose-LLM-v3:
    name: General Purpose LLM v3
    actionTypeId: .inference
    exposeConfig: true
    config:
      provider: "elastic"
      taskType: "chat_completion"
      inferenceId: ".gp-llm-v3-chat_completion"
      providerConfig:
        model_id: "gp-llm-v3"
  General-Purpose-LLM-v2:
    name: General Purpose LLM v2
    actionTypeId: .inference
    exposeConfig: true
    config:
      provider: "elastic"
      taskType: "chat_completion"
      inferenceId: ".gp-llm-v2-chat_completion"
      providerConfig:
        model_id: "gp-llm-v2"
  General-Purpose-LLM-v1:
    name: General Purpose LLM v1
    actionTypeId: .inference
    exposeConfig: true
    config:
      provider: "elastic"
      taskType: "chat_completion"
      inferenceId: ".rainbow-sprinkles-elastic"
      providerConfig:
        model_id: "rainbow-sprinkles"
