# Security Essentials tier config

## Cloud settings
xpack.cloud.serverless.product_tier: essentials

### Workflows plugins should not be enabled in this tier
workflowsManagement.enabled: false
workflowsExecutionEngine.enabled: false

### Agent Builder should not be enabled in this tier
xpack.agentBuilder.enabled: false
