# Security Essentials tier config

## Fine-tune the security solution essentials feature privileges. These feature privilege overrides are set individually for each project type. Also, refer to `serverless.yml` for the project-agnostic overrides.
xpack.features.overrides:
  dashboard:
    privileges:
      ### Dashboard's `All` feature privilege should implicitly grant `All` access to Maps and Visualize features.
      all.composedOf:
        - feature: "maps"
          privileges: [ "all" ]
        - feature: "visualize"
          privileges: [ "all" ]
      ### Dashboard's `Read` feature privilege should implicitly grant `Read` access to Maps and Visualize features.
      ### Additionally, it should implicitly grant privilege to create short URLs in Visualize app.
      read.composedOf:
        - feature: "maps"
          privileges: [ "read" ]
        - feature: "visualize"
          privileges: [ "read" ]
    ### All Dashboard sub-feature privileges should be hidden: reporting capabilities will be granted via dedicated
    ### Reporting feature and short URL sub-feature privilege should be granted for both `All` and `Read`.
    subFeatures.privileges:
      download_csv_report.disabled: true
      generate_report.disabled: true
      store_search_session.disabled: true
      url_create:
        disabled: true
        includeIn: "read"
  dashboard_v2:
    privileges:
      ### Dashboard's `All` feature privilege should implicitly grant `All` access to Maps and Visualize features.
      all.composedOf:
        - feature: "maps_v2"
          privileges: [ "all" ]
        - feature: "visualize_v2"
          privileges: [ "all" ]
      ### Dashboard's `Read` feature privilege should implicitly grant `Read` access to Maps and Visualize features.
      ### Additionally, it should implicitly grant privilege to create short URLs in Visualize app.
      read.composedOf:
        - feature: "maps_v2"
          privileges: [ "read" ]
        - feature: "visualize_v2"
          privileges: [ "read" ]
    ### All Dashboard sub-feature privileges should be hidden: reporting capabilities will be granted via dedicated
    ### Reporting feature and short URL sub-feature privilege should be granted for both `All` and `Read`.
    subFeatures.privileges:
      download_csv_report.disabled: true
      generate_report.disabled: true
      store_search_session.disabled: true
      url_create:
        disabled: true
        includeIn: "read"
  discover.hidden: true
  discover_v2.hidden: true
  dashboard.hidden: true
  dashboard_v2.hidden: true
  visualize.hidden: true
  visualize_v2.hidden: true
  maps.hidden: true
  maps_v2.hidden: true
  ### Security's feature privileges are fine-tuned to grant access to Discover, Dashboard, Maps, and Visualize apps.
  siemV2:
    privileges:
      ### Security's `All` feature privilege should implicitly grant `All` access to Discover, Dashboard, Maps, and
      ### Visualize features.
      all.composedOf:
        - feature: "discover_v2"
          privileges: [ "all" ]
        - feature: "dashboard_v2"
          privileges: [ "all" ]
        - feature: "visualize_v2"
          privileges: [ "all" ]
        - feature: "maps_v2"
          privileges: [ "all" ]
      # Security's `Read` feature privilege should implicitly grant `Read` access to Discover, Dashboard, Maps, and
      # Visualize features. Additionally, it should implicitly grant privilege to create short URLs in Discover,
      ### Dashboard, and Visualize apps.
      read.composedOf:
        - feature: "discover_v2"
          privileges: [ "read" ]
        - feature: "dashboard_v2"
          privileges: [ "read" ]
        - feature: "visualize_v2"
          privileges: [ "read" ]
        - feature: "maps_v2"
          privileges: [ "read" ]

  ### Security's feature privileges are fine-tuned to grant access to Discover, Dashboard, Maps, and Visualize apps.
  siem:
    privileges:
      ### Security's `All` feature privilege should implicitly grant `All` access to Discover, Dashboard, Maps, and
      ### Visualize features.
      all.composedOf:
        - feature: "discover_v2"
          privileges: [ "all" ]
        - feature: "dashboard_v2"
          privileges: [ "all" ]
        - feature: "visualize_v2"
          privileges: [ "all" ]
        - feature: "maps_v2"
          privileges: [ "all" ]
        - feature: "savedQueryManagement"
          privileges: [ "all" ]
      # Security's `Read` feature privilege should implicitly grant `Read` access to Discover, Dashboard, Maps, and
      # Visualize features. Additionally, it should implicitly grant privilege to create short URLs in Discover,
      ### Dashboard, and Visualize apps.
      read.composedOf:
        - feature: "discover_v2"
          privileges: [ "read" ]
        - feature: "dashboard_v2"
          privileges: [ "read" ]
        - feature: "visualize_v2"
          privileges: [ "read" ]
        - feature: "maps_v2"
          privileges: [ "read" ]
        - feature: "savedQueryManagement"
          privileges: [ "read" ]
  ### Visualize feature is hidden in Role management since it's automatically granted by Dashboard feature.
  visualize:
    ### The short URL sub-feature privilege should be always granted.
    subFeatures.privileges.url_create.includeIn: "read"
  visualize_v2:
    hidden: true
    ### The short URL sub-feature privilege should be always granted.
    subFeatures.privileges.url_create.includeIn: "read"
