version: '2'
services:
  kibana_docs:
    container_name: $KIBANA_DOCS_CONTAINER_NAME
    build:
      context: $KIBANA_DOCS_CONTEXT/tasks/docker_docs
    volumes:
      - $KIBANA_DOCS_CONTEXT/docs:/home/kibana/ascii_docs
