steps:
  - block: "Purge deployment"
    prompt: "Fill out the details to shutdown a PR deployment"
    fields:
      - text: "Pull Request Number"
        key: "kibana-pull-request"
    if: "build.env('KIBANA_PULL_REQUEST') == null || build.env('KIBANA_PULL_REQUEST') == ''"

  - command: .buildkite/scripts/steps/cloud/purge_deployment.sh
    label: Purge a cloud deployment
    timeout_in_minutes: 10
    agents:
      image: family/kibana-ubuntu-2004
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-2
