# Kibana is served by a backend server. This controls which port to use.
port: 5601

# The host to bind the server to
host: "0.0.0.0"

# The Elasticsearch instance to use for all your queries
elasticsearch: "http://localhost:9200"

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create an new index if it doesn't already exist.
kibanaIndex: ".kibana"

# The default application to laad.
defaultAppId: "discover"

# Time in seconds to wait for responses from the backend or elasticsearch.
# Note this should always be higher than "shard_timeout"
request_timeout: 60

# Time in milliseconds for elasticsearch to wait for responses from shards
# Note this should always be lower than "request_timeout"
shard_timeout: 30000