name: Add author:obs-ux-management label to PRs

on:
  pull_request_target:
    types: [opened]

jobs:
  label-obs-ux-management-team:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Label if author is in the obs-ux-management team
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const obsUxManagementTeam = [
              "maryam-saeidi",
              "jasonrhodes",
              "kdelemme",
              "mgiota",
              "shahzad31",
              "fkanout",
              "dominiqueclarke",
              "justinkambic",
              "cesco-f",
              "benakansara",
              "baileycash-elastic"
            ]; // GitHub usernames
            const label = "author:obs-ux-management";

            const author = context.payload.pull_request.user.login;

            if (obsUxManagementTeam.includes(author)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label],
              });
            }
