name: Add to APM Project
on:
  issues:
    types:
      - labeled
jobs:
  add_to_project:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'Team:apm'
    steps:
      - uses: octokit/graphql-action@v2.x
        id: add_to_project
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation add_to_project($projectid:ID!,$contentid:ID!) {
              addProjectNextItem(input:{projectId:$projectid contentId:$contentid}) {
                projectNextItem {
                  id
                }
              }
            }
          projectid: ${{ env.PROJECT_ID }}
          contentid: ${{ github.event.issue.node_id }}
        env:
          PROJECT_ID: "PN_kwDOAGc3Zs0VSg"
          GITHUB_TOKEN: ${{ secrets.APM_TECH_KIBANA_USER_TOKEN }}
      - uses: octokit/graphql-action@v2.x
        id: label_team
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          query: |
            mutation label_team($projectid:ID!,$itemid:ID!,$fieldid:ID!,$value:String!) {
              updateProjectNextItemField(input: { projectId:$projectid itemId:$itemid fieldId:$fieldid value:$value }) {
                projectNextItem {
                  id
                }
              }
            }
          projectid: ${{ env.PROJECT_ID }}
          itemid: ${{ fromJSON(steps.add_to_project.outputs.data).addProjectNextItem.projectNextItem.id }}
          fieldid: "MDE2OlByb2plY3ROZXh0RmllbGQ0NDE0Ng=="
          value: "c33f5c54"
        env:
          PROJECT_ID: "PN_kwDOAGc3Zs0VSg"
          GITHUB_TOKEN: ${{ secrets.APM_TECH_KIBANA_USER_TOKEN }}
