on:
  pull_request_target:
    branches-ignore:
      - main
    types:
      - opened

jobs:
  approve:
    name: Auto-approve backport
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'backport') &&
      contains(github.base_ref, 'kibanamachine:backport')
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.KIBANAMACHINE_TOKEN }}
