name: rule-type-param-changes-comment

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    paths:
      - 'x-pack/platform/plugins/shared/alerting/server/integration_tests/__snapshots__/serverless_upgrade_and_rollback_checks.test.ts.snap'

jobs:
  rule-type-param-changes-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `@${context.payload.pull_request.user.login}, it looks like you're updating the parameters for a rule type!

            Please review the [guidelines](https://docs.elastic.dev/reops/developer-guide/best-practices-rules#upgrades-and-rollbacks) for making additive changes to rule type parameters and determine if your changes require an intermediate release.

            <!-- Rule type parameter change comment marker -->
            `;

            const { data: existingComments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = existingComments.find(c => {
              return c.body.includes('<!-- Rule type parameter change comment marker -->')
            })

            if (!botComment) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              })
            }
