#
# This workflow sets the status check `synthetics-stack-e2e` instantly to 'failure'
# the synthetics-stack-e2e.yml is triggered with a PR comment and is responsible for setting it to success or failure.
#
name: synthetics # This name needs to be the same as in synthetic-stack-e2e.yml

on:
  pull_request:
    paths:
      - "x-pack/plugins/synthetics/**"

jobs:
  synthetics-stack-e2e: # This name needs to be the same as in synthetic-stack-e2e.yml
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Comment "/synthetics-stack-e2e" on the PR to trigger the synthetics stack e2e workflow. That job workflow is responsible for setting this status check to success or failure."'
          exit 1
